spring.application.name=sistema-gerenciamento-escolar

spring.datasource.url=jdbc:mysql://localhost:3306/sms?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345

# Remova a linha do dialect (Hibernate detecta automaticamente)
# spring.jpa.properties.hibernate.dialect =

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=DEBUG